# Plugin repository allowlist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.

---
triggers:
- repos:
  - kubesphere
  - kubesphere-sigs

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
    config/prow/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config
      gzip: true

slack:
  mergewarnings:
  - repos:
    - kubesphere/kubesphere
    - kubesphere/console
    - kubesphere/ks-installer
    - kubesphere/kubekey
    channels:
    - prow

lgtm:
- repos:
  - kubesphere/kubesphere
  - kubesphere/console
  - kubesphere/ks-installer
  - kubesphere/kubekey
  store_tree_hash: true

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

label:
  additional_labels:
    # These labels are used to make Tide merge with a non-default merge method
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash
    # Ingore generating a changelog item
    - no-changelog

repo_milestone:
  '':
    maintainers_id: 4979590
    maintainers_team: milestone-maintainers

plugins:
  kubesphere:
    plugins:
    - approve
    - assign
    - cla
    - golint
    - help
    - hold
    - label
    - lgtm
    - pony
    - cat
    - lifecycle
    - retitle
    - size
    - skip
    - slackevents
    - trigger
    - verify-owners
    - wip

  kubesphere-sigs:
    plugins:
    - approve
    - assign
    - cla
    - golint
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - retitle
    - size
    - skip
    - slackevents
    - trigger
    - verify-owners
    - wip

  kubesphere/kubesphere:
    plugins:
    - milestone
    - milestonestatus
    - release-note
    - require-matching-label

  kubesphere/console:
    plugins:
    - milestone
    - milestonestatus
    - release-note
    - require-matching-label

  kubesphere/ks-devops:
    plugins:
    - milestone
    - milestonestatus

external_plugins:
  kubesphere:
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request
  - name: needs-rebase
    events:
    - pull_request
